name: Generate image tag
description: "Workaround composite action to obtain an image tag in an expected format of on-premises k8s-deploy"
author: MP-ES
branding:
  icon: "tag"
  color: "purple"
inputs:
  registry:
    description: "Server address of Docker registry. If not set then will default to Docker Hub"
    required: false
    default: "hub.docker.com"
  image:
    description: "The name of docker image."
    required: true
outputs:
  tag:
    description: "Tag that must to be assigned to docker image"
    value: ${{ steps.tag.outputs.value }}
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/validate.sh
      shell: bash
      env:
        INPUT_REGISTRY: ${{ inputs.registry }}
        INPUT_IMAGE: ${{ inputs.image }}
    - id: tag
      run: echo "::set-output name=value::${{ env.registry }}/${{ github.event.repository.name }}/${{ env.image }}:${{ env.SHA8 }}"
      shell: bash
      env:
        SHA8: ${GITHUB_SHA::8}
